### ISSUE TITLE
Question re: Aarakshan (Reservation)

### ISSUE THREAD

**Issue by apoorvalal** [aryan096/Uttar-Pradesh-2015-2021-Panchayat-Candidates#2]
Hi all,

Thanks for the great work on this. A coauthor and I also scraped the 2015 data for a different project, but the merge w 2021 data you guys have done is particularly useful.

I was wondering if the 'aarakshan' column from the raw pages could be kept in the processing steps so that `master.csv` retains it for both 2015 and 2021. I know that they're present in the 2015 data [e.g. [here](https://github.com/in-rolls/up-2015-panchayat-ge-results/blob/master/data/%E0%A4%85%E0%A4%AE%E0%A5%87%E0%A4%A0%E0%A5%80-%E0%A4%97%E0%A5%8D%E0%A4%B0%E0%A4%BE%E0%A4%AE%20%E0%A4%AA%E0%A4%82%E0%A4%9A%E0%A4%BE%E0%A4%AF%E0%A4%A4%20%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%A7%E0%A4%BE%E0%A4%A8.csv) - पद का आरक्षण]. In theory, one could reverse-engineer this from the winner's caste variable (if there was perfect compliance and no reserved candidates won in non-reserved cycles, which is a depressing thought), but I found a few values of `winner_caste_2021` that I couldn't map cleanly to reservation categories.

![image](https://user-images.githubusercontent.com/12086926/156243296-8b7ca87a-df91-4899-8313-b6df9771c948.png)

I'm interested in studying patterns in incumbency when GPs switch from open to reserved seats (non SC/ST subset of incumbents can't run again) and vice versa (SC/ST incumbents can run again). 
Happy to discuss this in private if these are variables of particular interest to you.

**Comment by aryan096** [comment]
Hello Apoorva, 

I believe the reservation status of the panchayat in 2021 was removed during our processing since it wasn't needed. Good catch! I am attaching a file that has information about reservation in 2021. Perhaps you could join this with our master.csv? 

Here is a link to 2021 data - https://drive.google.com/file/d/1MWZK6dGovE1AffP7YUIp1112SUC3T5a2/view?usp=sharing

Let me know if this solves your issue. Could you also share the master.csv after you have joined with the reservation status in 2021? We would like to update our repo since this information could be useful to others. :)
